<?php

/**
 * PluginToken
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfCacophonyPlugin
 * @subpackage model
 * @author     Janusz Slota <janusz.slota@nixilla.com>
 */
abstract class PluginToken extends BaseToken
{
 /**
  * Is token expired
  * 
  * @return boolean
  */
  public function isExpired()
  {
    if ($this->getDateTimeObject('expires_at')->getTimestamp() < time()) return true;
    else return false;
  }
}