<?php

/**
 * PluginTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfCacophonyPlugin
 * @subpackage model
 * @author     Janusz Slota <janusz.slota@nixilla.com>
 */
class PluginTokenTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginTokenTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginToken');
  }
}