Token:
  columns:
    provider:   { type: string(30) }
    content:    { type: array(10000) }
    sf_guard_user_id: { type: integer }
    expires_at: { type: timestamp }
    providers_user_id: { type: string(255) }
  relations:
    User:
      class: sfGuardUser
      onDelete: CASCADE
      foreignAlias: Tokens
  options:
    symfony:
      form: false
      filter: false